[config]
schemaVersion = "0.0.1"

[package]
namespace = "loaforc"
name = "loaforcsSoundAPI"
description = "A general use library to replace sounds in Unity games."
websiteUrl = "https://github.com/loaforcsSoundAPI/loaforcsSoundAPI"
containsNsfwContent = false
[package.dependencies]
BepInEx-BepInExPack = "5.4.2100"

[build]
icon = "./icon.png"
readme = "../../README.md"
outdir = "../../Packages"

[[build.copy]]
source = "../bin/Release/netstandard2.1/me.loaforc.soundapi.dll"
target = "BepInEx/plugins/loaforcsSoundAPI/"

[[build.copy]]
source = "../../LICENSE"
target = "LICENSE"

[[build.copy]]
source = "./CHANGELOG.md"
target = "CHANGELOG.md"

[publish]
# https://thunderstore.io/api/experimental/community/
communities = [ "lethal-company", "repo", "peak" ]
[publish.categories]
# https://thunderstore.io/api/experimental/community/lethal-company/category/
lethal-company = [ "libraries", "mods", "tools", "audio", "clientside" ]
repo = [ "libraries", "mods", "tools", "audio" ]
peak = [ "libraries", "mods", "tools", "audio", "client" ]